Cleanup + support for OpsGenie's new entity names.
StackStorm-Exchange/stackstorm-opsgenie pull request #16
Opened 2020-11-17 16:28 UTC by nzlosh

This pull request removes the executable file attribute from files.
Standardises the code format using Black.
Add support for OpsGenie's new entity names.

2020-12-01 18:02 UTC, nmaludy requested changes
One small performance related change, nothing major.

2020-12-01 18:02 UTC, nmaludy commented on actions/create_alert.py
> +    if type_ == "user" and re.match(r"^[^@]+@[^@]+$", form):
Would be more performant to compile these regexes and use the compiled patterns to match, especially since this is called in a loop.

2021-08-10 07:16 UTC, nzlosh commented
Anyone able to merge this? @armab ?

2021-08-10 14:58 UTC, armab commented
Sure, thanks @nzlosh !

2021-08-10 14:58 UTC, armab approved these changes

2021-08-10 14:58 UTC, merged

2021-08-11 07:41 UTC, nzlosh commented
Thanks @armab :+1: